use customer_behaviour;
select * from customers1;

-- 1 what is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as total_revenue
from customers1
group by gender;

-- 2 which customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customers1
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customers1 ) ;

-- 3 which are top 5 products with highest average review rating
select item_purchased, avg(review_rating) as avrg
from customers1
group by item_purchased
order by avrg desc
limit 5;

-- 4 compare the average amount between standard and express shipping
select shipping_type, avg(purchase_amount)
from customers1
where shipping_type in ("Standard", "Express")
group by shipping_type;

select * from customers1;

-- 5 do subscribed customers spend more? compare average spend and total revenue between subs and non subs
select subscription_status, sum(purchase_amount) as total_reeevenue, round(avg(purchase_amount),2) as avg_spent ,count(customer_id)
from customers1
where subscription_status in ("Yes", "No")
group by subscription_status;

-- 6 which 5 products have the highrest percentage of purchase with disscounts applied
select item_purchased, round(100 * sum( case when discount_applied = "Yes" then 1 else 0 end )/ count(*),2) as discount_rate
from customers1
group by item_purchased 
order by discount_rate desc
limit 5;

-- 7 segment customers into new, returning, and loyal based on their totl number of previous purchases and show the count of each segment
with customer_type as (
select item_purchased,
case
	when previous_purchases  = 1 then "New"
	when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from customers1)
select customer_segment, count(*) "as no of customers"
from customer_type
group by customer_segment;

-- 8 what are the top 3 most purchased products with in each category

with csm as (select item_purchased,category, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customers1
group by category, item_purchased)
select item_rank, item_purchased, category, total_orders
from csm
where item_rank <=3;

select * from customers1;


-- 9 are customers repeat buyers(more than 5 previous prices) also likely to subscribe

select subscription_status, count(customer_id) as repeat_buyers 
from customers1
where previous_purchases >5
group by subscription_status;

-- 10 wt is the revenue contribution of each age group

select age_group, sum(purchase_amount) as revenue
from customers1
group by age_group
order by revenue desc ;



